networks:
    wp-network:
        name: ${PROJECT_NAME}-network

volumes:
    wp-data:
        name: ${PROJECT_NAME}-data

services:
    database:
        image: mariadb:10.11
        container_name: "${PROJECT_NAME}-database"
        volumes:
            - .docker/dbData:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
            MARIADB_USER: ${WORDPRESS_DB_USER}
            MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            MARIADB_RANDOM_ROOT_PASSWORD: 1
        networks:
            - wp-network
        mem_limit: ${DB_MEM_LIMIT:-512m}
        cpus: ${DB_CPUS:-1}

    wordpress:
        depends_on:
            - database
        build:
            context: .docker
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV:-dev} # dev | prod
        container_name: "${PROJECT_NAME}-wordpress"
        ports:
            - "${WORDPRESS_PORT}:80"
            - "9003:9003" #is dev
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
            XDEBUG: ${XDEBUG:-false}
            WORDPRESS_CONFIG_EXTRA: "define('DISABLE_WP_CRON', true);"
            WORDPRESS_PLUGINS: ${WORDPRESS_PLUGINS-contact-form-7}
            WP_CRON_INTERVAL: ${WP_CRON_INTERVAL:-60}
        volumes:
            - wp-data:/var/www/html/
            - ./wp-content:/var/www/html/wp-content/
            - ./var/log:/var/log/apache2
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - wp-network
        mem_limit: ${WORDPRESS_MEM_LIMIT:-1g}
        cpus: ${WORDPRESS_CPUS:-2}
