#!/bin/bash

wp theme delete twentytwentytwo twentytwentythree --allow-root

wp plugin deactivate --uninstall --all --allow-root

# shellcheck disable=SC2066
for n in $(cat wp-content/plugins.txt)
do
    wp plugin install "$n"  --allow-root
done

for n in $(cat wp-content/pluginsDev.txt)
do
    wp plugin install "$n"  --activate  --allow-root
done

wp plugin update --all --allow-root



DIR="./wp-content"
USER=www-data
GROUP=www-data
USER_ID=$(stat -c '%u' ${DIR})
GROUP_ID=$(stat -c '%g' ${DIR})

echo "${USER_ID}" > /root/uid
echo "${GROUP_ID}" > /root/gid
usermod -u "${USER_ID}" ${USER}
groupmod -g "${GROUP_ID}" ${GROUP}
chown -R ${USER}:${GROUP} ./
chmod -R 775 ./wp-content
